# Generated by Django 2.2.4 on 2019-09-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='static_criminal',
            old_name='count',
            new_name='counter',
        ),
    ]
