# Generated by Django 2.2.5 on 2019-09-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_1_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz_description', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_description', models.CharField(blank=True, max_length=100, null=True)),
                ('view', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('submenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_2_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_position', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_position', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz_phone', models.IntegerField(blank=True, max_length=100, null=True)),
                ('name_ru_phone', models.IntegerField(blank=True, max_length=100, null=True)),
                ('name_uz_admition_days', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru_admition_days', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_3_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('view', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('submenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='List_1_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz_description', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_description', models.CharField(blank=True, max_length=100, null=True)),
                ('view', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='List_2_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz_description', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_description', models.CharField(blank=True, max_length=100, null=True)),
                ('view', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='List_3_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='List_4_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_title', models.CharField(blank=True, max_length=100, null=True)),
                ('view', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.CreateModel(
            name='List_5_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz_description', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru_description', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Submenu')),
            ],
        ),
        migrations.RemoveField(
            model_name='listcontent',
            name='submenu',
        ),
        migrations.DeleteModel(
            name='DetailContent',
        ),
        migrations.DeleteModel(
            name='ListContent',
        ),
    ]
