# Generated by Django 2.2.5 on 2019-09-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190907_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_name_uz', models.TextField(blank=True, null=True)),
                ('description_name_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_name_uz', models.TextField(blank=True, null=True)),
                ('description_name_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_name_uz', models.TextField(blank=True, null=True)),
                ('description_name_ru', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type_form',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Type_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type_news',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='detail_2_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='detail_3_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='list_1_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='list_2_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='list_3_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='list_4_content',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='list_5_content',
            name='submenu',
        ),
        migrations.DeleteModel(
            name='Detail_1_Content',
        ),
        migrations.DeleteModel(
            name='Detail_2_Content',
        ),
        migrations.DeleteModel(
            name='Detail_3_Content',
        ),
        migrations.DeleteModel(
            name='List_1_Content',
        ),
        migrations.DeleteModel(
            name='List_2_Content',
        ),
        migrations.DeleteModel(
            name='List_3_Content',
        ),
        migrations.DeleteModel(
            name='List_4_Content',
        ),
        migrations.DeleteModel(
            name='List_5_Content',
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type_news'),
        ),
        migrations.AddField(
            model_name='forms',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type_form'),
        ),
    ]
