# Generated by Django 2.2.4 on 2019-09-11 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190910_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='International_busines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
