# Generated by Django 2.2.4 on 2019-09-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190913_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='type',
        ),
    ]
