# Generated by Django 2.2.4 on 2019-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_criminal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='international_busines',
            old_name='description_ru',
            new_name='full_content_ru',
        ),
        migrations.RenameField(
            model_name='international_busines',
            old_name='description_uz',
            new_name='full_content_uz',
        ),
        migrations.AddField(
            model_name='international_busines',
            name='short_content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='international_busines',
            name='short_content_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
