# Generated by Django 2.2.4 on 2019-09-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190908_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'criminal_type',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'region',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Static_criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('criminal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Criminal_type')),
                ('region', models.ManyToManyField(blank=True, null=True, to='app.Region')),
            ],
        ),
        migrations.AddField(
            model_name='criminal',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Criminal_type'),
            preserve_default=False,
        ),
    ]
