# Generated by Django 2.2.4 on 2019-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190911_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='international_busines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
