# Generated by Django 2.2.4 on 2019-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190909_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static_criminal',
            name='region',
            field=models.ManyToManyField(to='app.Region'),
        ),
    ]
